version: '3'
services:
  user-database:
    image: mysql
    container_name: user-database
    command: mysqld --lower_case_table_names=1 --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: "user"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "salocal"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped

volumes:
  mysql_data:
